[project]
name = "hmeg"
version = "0.1.0"
dependencies = [
  "mmengine",
  "more-itertools",
  "numpy",
  "positional-encodings[pytorch]",
  "tqdm",
]

[build-system]
requires = ["setuptools", "torch>=2,<2.1"]

[tool.setuptools.packages.find]
include = ["hmeg"]
